runtime: go
api_version: go1
service: apicaller

handlers:
- url: /.*
  script: _go_app

env_variables:
  ALPHAVANTAGEAPIKEY: 'demo'
#overwriting ALPHAVANTAGEAPIKEY in uncommited, local file:
includes:
- apikey.yaml