runtime: python37
#runtime: go
#api_version: go1
service: default

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
- url: /static
  static_dir: static
- url: /.*
#  script: _go_app
  script: auto
