runtime: python27
api_version: 1
service: charter
threadsafe: no

handlers:
- url: /.*
  script: main.app

libraries:
- name: numpy
  version: "1.6.1"
- name: matplotlib
  version: "1.2.0"
- name: "six"
  version: "1.9.0"

